# ---------------------------------------------------------------------------------
#
# Project : 3258.1 Sécurité Informatique - Labo LDAP
# Author  : Nima Dekhli <nima@dekhli.ch>
# Date    : 2024-04-23
# 
# All source code is freely available at https://github.com/ylked/3258-1-labo-ldap
#
# ------------------------------ LICENSE ------------------------------------------
#
# Copyright (c) 2024 Nima Dekhli
# 
# Permission is hereby granted, free of charge, to any person obtaining 
# a copy of this software and associated documentation files (the “Software”), 
# to deal in the Software without restriction, including without limitation the 
# rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell 
# copies of the Software, and to permit persons to whom the Software is furnished 
# to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all 
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, 
# INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A 
# PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT 
# HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION 
# OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE 
# SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#
# ---------------------------------------------------------------------------------


version: "3.8"
services:
  ldap-service:
    container_name: ldap
    image: ylked/ldap

    environment:
      - LDAP_ORGANISATION=NDE
      - LDAP_DOMAIN=ylked.ch
      - LDAP_ADMIN_PASSWORD=admin

    healthcheck:
      test: ldapsearch -x -D "cn=admin,dc=ylked,dc=ch" -w admin -b "dc=ylked,dc=ch"
      start_period: 15s
      start_interval: 3s
      timeout: 2s

    command: --copy-service

  phpldapadmin-service:
    container_name: phpldapadmin
    image: osixia/phpldapadmin:0.9.0
    ports:
      - 6443:443

    environment:
      - PHPLDAPADMIN_LDAP_HOSTS=ldap-service


  server-service:
    container_name: server
    image: ylked/ldap-flask
    ports:
      - 8088:5000
    
    environment:
      - "FLASKLDAP_HOSTNAME=ldap-service"
      - "FLASKLDAP_BASE=dc=ylked,dc=ch"

    depends_on:
      ldap-service:
        condition: service_healthy
      
  testing-service:
    container_name: testing
    image: ylked/ldap-flask
    command: python3 test.py

    depends_on: 
      ldap-service:
        condition: service_healthy
    
    environment:
      - "FLASKLDAP_HOSTNAME=ldap-service"
      - "FLASKLDAP_BASE=dc=ylked,dc=ch"
